### ISSUE TITLE
Cursor loses track of position

### ISSUE THREAD

**Issue by rboy1** [daltskin/SmartThingsTerminal#12]
While navigating the app the cursor loses track of it's position while navigating.

1. Start the app
2. Go full screen
3. Cursor loses track and is randomly located on the screen

Another way:
1. Start the app
2. Select Locations (I have multiple)
3. Press Home to go back to the main menu
4. (The cursor is still on the right hand menu), press the Left arrow key
5. Cursor loses track and is relocates itself to a random location on the STT box on top (instead of the main menu on the right)

**Comment by daltskin** [comment]
@rboy1 this should now be fixed in the latest release.
