### ISSUE TITLE
[FEATURE] Missing location information

### ISSUE THREAD

**Issue by rboy1** [daltskin/SmartThingsTerminal#19]
There appears to be additional information in the location API's. Can that also be displayed:

> {
"locationId": "6b3d1909-1e1c-43ec-adc2-5f941de4fbf9",
"name": "Home",
"countryCode": "USA",
"latitude": 45.00708112,
"longitude": -93.11223629,
"regionRadius": 150,
"temperatureScale": "F",
"timeZoneId": "America/Chicago",
"locale": "en"
}

**Comment by daltskin** [comment]
Thanks for raising @rboy1 - looking into it.

**Comment by daltskin** [comment]
@rboy1 try the latest release - should now show the full details for locations
