### ISSUE TITLE
Thanks! - Subscriptions 403

### ISSUE THREAD

**Issue by doug62** [daltskin/SmartThingsTerminal#26]
Thanks for an excellent example of C#/SmartThings.

I get a 403 when i try subscriptions - I'm I doing something wrong (it does say untested....)

**Comment by daltskin** [comment]
I get the same - it's the API returning the 403s.

In Postman if you hit: 

https://api.smartthings.com/v1/installedapps/{installed-app-id}/subscriptions with valid token you'll get a 403.

**Comment by rboy1** [comment]
I'm getting a 401 now

**Comment by daltskin** [comment]
I've removed Subscriptions from STT since I've never been able to test it properly (even through the api).

**Comment by rboy1** [comment]
Thats very sad :( it would be great to have it there, can always see how to fix it in future. This is the most comprehensive tool I've seen

**Comment by daltskin** [comment]
Thanks for the feedback!  Was subscriptions ever working for you?  I have no way to test, happy to re-instate it if someone can verify it was working.  The underlying sdk still supports it, it's just removed from SST for the time being.

**Comment by rboy1** [comment]
Been testing it but unfortunately no, I eventually end up with a 403 also even for custom apps. Let me ping SmartThings support and see what’s going on.

**Comment by rboy1** [comment]
According to ST subscriptions cannot be created using a PAT but an Access Token from a SmartApp or OAuth integration so they can be retrieved using a PAT. It feature can be safely dropped until ST changes the architecture.

**Comment by daltskin** [comment]
Thanks @rboy1 for the update - will close this now.
