### ISSUE TITLE
Error while trying to enumerate devices

### ISSUE THREAD

**Issue by rboy1** [daltskin/SmartThingsTerminal#29]
When I try enumerate all devices it throws an error:
> Error Object reference not set to an instance of an object

Also when enumerating subscriptions it gives and Error 403 Error calling ListSubscriptions

**Comment by rboy1** [comment]
Everything else is working, but devices are the key ones

**Comment by rboy1** [comment]
Error is coming from line 32 of `devices.cs`
> if (STClient.GetAllDevices().Items?.Count > 0)

It looks like Items is null, the underlying SmartThingsNet library isn't able to enumerate

**Comment by daltskin** [comment]
Updated SDK, this should now be resolved

**Comment by rboy1** [comment]
Yes that fixes one issue, but noticed another one causing a crash. Not all devices have rooms which is causing a crash in devices.cs line 153

> roomName = STClient.GetAllRooms(device.LocationId).Items.Where(r => r.RoomId.ToString().Equals(device.RoomId))?.FirstOrDefault().Name;

**Comment by rboy1** [comment]
Fix here:
https://github.com/daltskin/SmartThingsTerminal/pull/33

**Comment by rboy1** [comment]
It works fine with your SDK update and the patch above. Will you be releasing a new version?

**Comment by daltskin** [comment]
Your fixes are merged!
