### ISSUE TITLE
Unable to build in VS2019

### ISSUE THREAD

**Issue by rboy1** [daltskin/SmartThingsTerminal#43]
I noticed the .net version was bumped to 6.0. Any specific reason? The problems is that .NET6.0 isn't supported on anything older than VS2022 and I cannot upgrade to VS2022 for other reasons.

Wondering if the .NET5.0 target was creating some issue. Am trying to debug the app but can't run it from VS2019 for this reason.

**Comment by daltskin** [comment]
Gotta keep up with the times :)

Suggested alternative, use VS Code 😀

![image](https://user-images.githubusercontent.com/1678318/175375991-eb89b380-2f61-4753-be7d-9ce5cc99d45b.png)

**Comment by rboy1** [comment]
Just as a note, changing the framework version to net5.0 and it works just fine with VS2019. Helps with backwards compatibility unless there is a specific need to target net6.0 :)

**Comment by daltskin** [comment]
@rboy1 glad you found a resolution - will close this now
