### ISSUE TITLE
Crash when trying to read devices

### ISSUE THREAD

**Issue by rboy1** [daltskin/SmartThingsTerminal#6]
Very neat tool.

Replication process:
1. Start app
2. Select devices, click enter
3. Select device under API description and click enter

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartThingsTerminal.Scenarios.Devices.Setup()
   at SmartThingsTerminal.Program.Init(Options opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SmartThingsTerminal.Program.Main(String[] args)
```

**Comment by daltskin** [comment]
Thanks @rboy1 for reporting - this can happen if you either have no devices registered (or use the wrong API key).

Will fix in next release.

**Comment by rboy1** [comment]
I have over 300 devices and the API key is correct because I can view the other items (Locations etc).

**Comment by daltskin** [comment]
Can you try again with the latest release: https://github.com/daltskin/SmartThingsTerminal/releases/tag/0.11.1

**Comment by rboy1** [comment]
It's not crashing anymore but it gives the following error:
> Unknown error calling API: An item with the same key has already been added.
Key: XXX iPhone

**Comment by daltskin** [comment]
Ah ok - this is a different bug (something I'll look at over the weekend).

I suspect you have more than 1 device with the same name - short term fix is to rename one of them.

I'll close this one and create a new bug.
